# Generated by Django 4.2.29 on 2026-03-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown on the blog listing page.', max_length=300)),
                ('body', models.TextField(help_text='Full blog post content. HTML is allowed.')),
                ('featured_image', models.ImageField(blank=True, help_text='Main image for the blog post.', null=True, upload_to='blog/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('daycare', 'Daycare'), ('one2one', 'One 2 One Training'), ('puppy_classes', 'Puppy Classes'), ('field_hire', 'Field Hire'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact inquiry',
                'verbose_name_plural': 'Contact inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
