# Generated by Django 5.2.10 on 2026-03-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sitesettings_cta_subtitle_sitesettings_cta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person giving the testimonial.', max_length=100)),
                ('dog_name', models.CharField(blank=True, help_text="Name of the person's dog (optional).", max_length=100)),
                ('quote', models.TextField(help_text='The testimonial text.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active testimonials are shown on the homepage.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
