# Generated by Django 5.2.10 on 2026-06-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_seed_service_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='training_text',
            field=models.TextField(default="<p>At Paws 4 Thought Dogs, we understand that every dog has unique needs and personality traits, which is why we offer personalized one-to-one training sessions. We will work with you and your dog to identify any areas of concern or behaviour issues that need to be addressed. We use positive reinforcement techniques to teach your dog new commands and behaviours, as well as provide solutions to any problem behaviours your dog may be exhibiting.</p><p>Our one-to-one training sessions are tailored to your specific needs, and can cover anything from basic obedience to advanced skills such as agility training. Sessions don't have to be on-site — our trainer can come to you, whether that's your home, a local park, or wherever your dog feels most comfortable. With our one-to-one training, you'll receive personalised attention and support throughout the entire training process, ensuring that you and your dog achieve your goals together. We are passionate about working with dogs and are committed to helping you develop a strong and positive relationship with your dog. Whether you're a first-time dog owner or a seasoned pro, our one-to-one training sessions are the perfect way to help your dog reach their full potential.</p>", help_text='One-to-one training section body text. HTML is allowed.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='welcome_text',
            field=models.TextField(default="Welcome to our dog day care website, serving the Berkshire and Buckinghamshire area! As a pet owner, you know that your dog deserves the best care and attention possible, and that's exactly what we provide. Our dog day care services offer a safe and fun environment for your dog to play, exercise and socialize with other dogs, all under the watchful eye of our experienced and caring staff. Whether you're at work, running errands or simply need a break, we're here to give your dog the attention and care they need, so you can have peace of mind knowing that your dog is happy and well taken care of.", help_text='Welcome section body text. HTML is allowed.'),
        ),
    ]
