# Generated by Django 5.2.10 on 2026-07-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_sitesettings_training_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepricing",
            name="boarding_price_per_night",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Overnight boarding price per night, used by monthly invoicing. Boarding lines on draft invoices bill £0.00 until this is set.",
                max_digits=6,
            ),
        ),
    ]
