# Generated by Django 5.2.10 on 2026-07-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_servicepricing_boarding_price_per_night"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepricing",
            name="owner_transport_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount off the daycare day rate when the owner both drops off and picks up that day. 0 = no discount.",
                max_digits=6,
            ),
        ),
    ]
