# Generated by Django 5.2.10 on 2026-09-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_servicepricing_owner_transport_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricing',
            name='day_care_price_1_day',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Day care price per day for dogs booked in one day a week (also ad hoc dogs).', max_digits=6),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='day_care_price_2_to_4_days',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Day care price per day for dogs booked in two to four days a week.', max_digits=6),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='day_care_price_5_days',
            field=models.DecimalField(decimal_places=2, default=33.0, help_text='Day care price per day for dogs booked in five days a week.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='servicepricing',
            name='day_care_price',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Legacy flat day care price. Invoicing now uses the per-week tiers below; kept for older app versions.', max_digits=6),
        ),
    ]
