# Generated by Django 5.2.10 on 2026-02-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_breed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
