# Generated by Django 5.2.10 on 2026-02-01 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_date_change_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("PHOTO", "Photo"), ("VIDEO", "Video")], max_length=10
                    ),
                ),
                ("file", models.FileField(upload_to="group_media/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="group_media/thumbnails/"
                    ),
                ),
                ("caption", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Group media",
                "ordering": ["-created_at"],
            },
        ),
    ]
