# Generated by Django 5.2.10 on 2026-02-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_group_media'),
        ('api', '0007_datechangerequest_approved_at_and_more'),
    ]

    operations = [
    ]
