# Generated by Django 5.2.10 on 2026-02-01 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20260201_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='dog_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='media_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video')], default='PHOTO', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='dog_photos/thumbnails/'),
        ),
    ]
