# Generated by Django 5.2.10 on 2026-02-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_photo_image_photo_file_photo_media_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.groupmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('media', 'user', 'emoji')},
            },
        ),
    ]
