# Generated by Django 5.2.10 on 2026-02-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_requests',
            field=models.BooleanField(default=False, help_text='Designates whether this user can approve/deny requests.'),
        ),
    ]
