# Generated by Django 5.2.10 on 2026-02-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_can_manage_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add_feed_media',
            field=models.BooleanField(default=False, help_text='Designates whether this user can upload media to the feed.'),
        ),
    ]
