# Generated by Django 5.2.11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_userprofile_can_reply_queries_supportquery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='additional_owners',
            field=models.ManyToManyField(blank=True, related_name='additional_dogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
