# Generated by Django 5.2.10 on 2026-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="staff_photos/"),
        ),
    ]
