# Generated by Django 5.2.10 on 2026-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_supportquery_has_unread_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Contact staff reply', 'verbose_name_plural': 'Contact staff replies'},
        ),
        migrations.AlterModelOptions(
            name='supportquery',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Contact staff message', 'verbose_name_plural': 'Contact staff messages'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_inquiries',
            field=models.BooleanField(default=False, help_text='Designates whether this user can view and respond to website contact inquiries.'),
        ),
    ]
