# Generated by Django 5.2.10 on 2026-04-11 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_groupmedia_tagged_dogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogWeekdayPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(help_text='1=Monday … 7=Sunday (matches isoweekday())')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_weekday_pickups', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_pickups', to='api.dog')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekday_pickups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dog__name', 'weekday'],
                'indexes': [models.Index(fields=['weekday', 'staff_member'], name='api_dogweek_weekday_226267_idx')],
                'unique_together': {('dog', 'weekday')},
            },
        ),
    ]
