# Generated by Django 5.2.10 on 2026-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_add_removed_status_to_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydogassignment',
            name='owner_brings',
            field=models.BooleanField(blank=True, help_text='Override for this date. Null = fall back to Dog.owner_brings_default.', null=True),
        ),
        migrations.AddField(
            model_name='dailydogassignment',
            name='owner_brings_time',
            field=models.TimeField(blank=True, help_text='Expected drop-off time when owner brings the dog on this date.', null=True),
        ),
        migrations.AddField(
            model_name='dailydogassignment',
            name='owner_collects',
            field=models.BooleanField(blank=True, help_text='Override for this date. Null = fall back to Dog.owner_collects_default.', null=True),
        ),
        migrations.AddField(
            model_name='dailydogassignment',
            name='owner_collects_time',
            field=models.TimeField(blank=True, help_text='Expected pick-up time when owner collects the dog on this date.', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner_brings_default',
            field=models.BooleanField(default=False, help_text='Owner usually drops this dog off at daycare (no staff pickup).'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner_brings_default_time',
            field=models.TimeField(blank=True, help_text='Expected default drop-off time when owner brings the dog.', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner_collects_default',
            field=models.BooleanField(default=False, help_text='Owner usually collects this dog from daycare (no staff drop-off home).'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner_collects_default_time',
            field=models.TimeField(blank=True, help_text='Expected default pick-up time when owner collects the dog.', null=True),
        ),
    ]
