# Generated by Django 5.2.10 on 2026-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_dog_sex_dob_is_spayed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="accepted_privacy_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user accepted the Privacy Policy.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="accepted_privacy_version",
            field=models.CharField(
                blank=True,
                help_text="Version/date of the Privacy Policy the user accepted.",
                max_length=20,
                null=True,
            ),
        ),
    ]
