# Generated by Django 5.2.10 on 2026-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_userprofile_accepted_privacy_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='registered_vet',
            field=models.TextField(blank=True, help_text="Owner's registered vet — typically the practice name, address and phone number.", null=True),
        ),
    ]
