# Generated by Django 5.2.10 on 2026-06-10 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_dog_registered_vet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailydogassignment',
            index=models.Index(fields=['date'], name='api_dailydo_date_dfd972_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydogassignment',
            index=models.Index(fields=['date', 'staff_member'], name='api_dailydo_date_b38802_idx'),
        ),
        migrations.AddIndex(
            model_name='datechangerequest',
            index=models.Index(fields=['status', 'original_date'], name='api_datecha_status_4af2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='datechangerequest',
            index=models.Index(fields=['status', 'new_date'], name='api_datecha_status_b4a520_idx'),
        ),
    ]
