# Generated by Django 5.2.10 on 2026-06-10 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycareSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_daily_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of dogs per day (daycare + boarding). Empty = unlimited.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daycare settings',
                'verbose_name_plural': 'Daycare settings',
            },
        ),
        migrations.AddField(
            model_name='closureday',
            name='capacity_override',
            field=models.PositiveIntegerField(blank=True, help_text='For REDUCED days: maximum number of dogs that can attend. Empty = use the default daily capacity.', null=True),
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vaccine name, e.g. DHP, Leptospirosis, Kennel Cough, Rabies', max_length=100)),
                ('date_administered', models.DateField()),
                ('expiry_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_30_sent', models.BooleanField(default=False)),
                ('reminder_7_sent', models.BooleanField(default=False)),
                ('expired_notice_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vaccinations', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='api.dog')),
            ],
            options={
                'ordering': ['-expiry_date'],
                'indexes': [models.Index(fields=['expiry_date'], name='api_vaccina_expiry__079542_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('NOTIFIED', 'Notified')], default='WAITING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='api.dog')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Waitlist entries',
                'ordering': ['date', 'created_at'],
                'indexes': [models.Index(fields=['date', 'status'], name='api_waitlis_date_f401dc_idx')],
                'unique_together': {('dog', 'date')},
            },
        ),
    ]
