# Generated by Django 5.2.10 on 2026-06-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_vaccinations_capacity_waitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportquery",
            name="staff_has_unread",
            field=models.BooleanField(
                default=False,
                help_text="True when the owner has sent a message staff have not yet viewed",
            ),
        ),
    ]
