# Generated by Django 5.2.10 on 2026-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_facilitydefect_facilitydefectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='address',
            field=models.TextField(blank=True, help_text='Home address used for pickups/drop-offs of this dog.', null=True),
        ),
    ]
