# Generated by Django 5.2.10 on 2026-06-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_dog_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='access_instructions',
            field=models.TextField(blank=True, help_text='How to access the home — keys, codes, gates, where the dog is kept.', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='general_notes',
            field=models.TextField(blank=True, help_text='General notes about the dog (behaviour, handling, misc).', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='van_placement',
            field=models.TextField(blank=True, help_text='Where the dog should sit in the van and any companion/seating notes.', null=True),
        ),
    ]
