# Generated by Django 5.2.10 on 2026-06-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_dog_access_instructions_dog_general_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='geocode_source',
            field=models.CharField(blank=True, choices=[('house', 'House-level match'), ('postcode', 'Postcode centroid'), ('failed', 'Could not geocode')], help_text='Precision of the cached coordinates.', max_length=10),
        ),
        migrations.AddField(
            model_name='dog',
            name='geocoded_address',
            field=models.TextField(blank=True, help_text='The address string the cached coordinates were derived from, used to detect staleness.', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, help_text='When the address was last geocoded.', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Cached latitude of the pickup address.', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Cached longitude of the pickup address.', null=True),
        ),
    ]
