# Generated by Django 5.2.10 on 2026-06-15 14:45

import re

from django.db import migrations, models


# Self-contained postcode matcher (kept inline so this migration is stable even
# if api.geocoding changes later). Mirrors geocoding.extract_postcode.
_PC_RE = re.compile(r'\b([A-Za-z]{1,2}\d[A-Za-z\d]?)\s*(\d[A-Za-z]{2})\b')


def _extract_postcode(text):
    if not text:
        return ''
    matches = list(_PC_RE.finditer(text))
    if not matches:
        return ''
    return f'{matches[-1].group(1).upper()} {matches[-1].group(2).upper()}'


def backfill_postcodes(apps, schema_editor):
    """Populate the new structured postcode field from existing free-text
    addresses. Dogs whose address has no recognisable postcode are left blank
    for staff to fill in."""
    Dog = apps.get_model('api', 'Dog')
    for dog in Dog.objects.exclude(address__isnull=True).exclude(address='').iterator():
        if (dog.postcode or '').strip():
            continue
        pc = _extract_postcode(dog.address)
        if pc:
            dog.postcode = pc
            dog.save(update_fields=['postcode'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_dog_geocode_source_dog_geocoded_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='postcode',
            field=models.CharField(blank=True, help_text='UK postcode of the pickup address; drives placement on the staff map (preferred over parsing the free-text address).', max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='geocoded_address',
            field=models.TextField(blank=True, help_text='The effective postcode the cached coordinates were derived from, used to detect staleness.', null=True),
        ),
        migrations.RunPython(backfill_postcodes, noop),
    ]
