# Generated by Django 5.2.10 on 2026-06-19 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_dog_postcode_alter_dog_geocoded_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmedia',
            options={'ordering': ['-created_at', '-id'], 'verbose_name_plural': 'Group media'},
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group_media__isnull', False), ('photo__isnull', True)), models.Q(('group_media__isnull', True), ('photo__isnull', False)), _connector='OR'), name='comment_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='dayoffrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('staff_member', 'date'), name='unique_active_day_off_per_staff_date'),
        ),
    ]
