# Generated by Django 5.2.10 on 2026-06-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_dogweekdaypickup_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydogassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PICKED_UP', 'With Team'), ('DROPPED_OFF', 'Returned'), ('REMOVED', 'Removed')], default='ASSIGNED', max_length=20),
        ),
    ]
