# Generated by Django 5.2.10 on 2026-06-20 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_dailydogassignment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingrequest',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Staff member the dog boards with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_boarding_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
