# Generated by Django 5.2.10 on 2026-07-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_facilitydefectcomment_vehicledefectcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="staff_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hex colour (#RRGGBB) identifying this staff member across the app. Blank = automatic.",
                max_length=7,
            ),
        ),
    ]
