# Generated by Django 5.2.10 on 2026-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_userprofile_staff_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydogassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("PICKED_UP", "With Team"),
                    ("DROPPED_OFF", "Returned"),
                    ("UNASSIGNED", "Unassigned"),
                    ("REMOVED", "Removed"),
                ],
                default="ASSIGNED",
                max_length=20,
            ),
        ),
    ]
