# Generated by Django 5.2.10 on 2026-07-03 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_alter_dailydogassignment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Home address used for pickups/drop-offs; copied to each dog on approval.",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        help_text="UK postcode of the pickup address; copied to each dog on approval.",
                        max_length=10,
                    ),
                ),
                (
                    "pickup_instructions",
                    models.TextField(
                        blank=True,
                        help_text="How staff should collect the dog(s) — keys, gates, where the dog waits.",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="Anything else the owner wants staff to know.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("denial_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_intake_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntakeDog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_spayed", models.BooleanField(default=False)),
                ("food_instructions", models.TextField(blank=True)),
                ("medical_notes", models.TextField(blank=True)),
                ("registered_vet", models.TextField(blank=True)),
                (
                    "daycare_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Requested day numbers (1-7) for daycare attendance.",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("ad_hoc", "Ad Hoc"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "created_dog",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Dog record created when the request was approved.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_dogs",
                        to="api.dog",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dogs",
                        to="api.intakerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
