# Generated by Django 5.2.10 on 2026-07-04 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_intakerequest_intakedog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-day billing rate override for this dog. Blank = standard day care price from Service Pricing. Staff-only field.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_manage_payments",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user can manage customer invoices and record payments.",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_year", models.PositiveSmallIntegerField()),
                ("period_month", models.PositiveSmallIntegerField(help_text="1-12")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("PART_PAID", "Partially paid"),
                            ("PAID", "Paid"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Set when the invoice is sent (send date + 14 days).",
                        null=True,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "xero_invoice_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "xero_invoice_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("xero_online_url", models.URLField(blank=True, default="")),
                ("xero_last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("xero_sync_error", models.TextField(blank=True, default="")),
                ("overdue_reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-period_year",
                    "-period_month",
                    "customer__first_name",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Number of attended days."),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "attendance_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ISO dates the dog attended, for owner transparency.",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_lines",
                        to="api.dog",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="api.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("XERO_ONLINE", "Paid online"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=15,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Recorded by staff"),
                            ("XERO", "Imported from Xero"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "xero_payment_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.invoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["payment_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="XeroConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "tenant_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("refresh_token", models.TextField(blank=True, default="")),
                ("access_token", models.TextField(blank=True, default="")),
                (
                    "access_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "oauth_state",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("oauth_state_created_at", models.DateTimeField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Xero connection",
                "verbose_name_plural": "Xero connection",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["period_year", "period_month"],
                name="api_invoice_period__1a614b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="api_invoice_status_d10657_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "VOID"), _negated=True),
                fields=("customer", "period_year", "period_month"),
                name="uniq_active_invoice_per_customer_period",
            ),
        ),
    ]
