# Generated by Django 5.2.10 on 2026-07-04 11:28

from django.db import migrations, models


def backfill_can_manage_boarding(apps, schema_editor):
    """Boarding approval was previously the can_manage_requests cohort's job
    (any staff could approve via the API, but alerts targeted that flag), so
    grant the new flag to those staff to keep approvals working on deploy."""
    UserProfile = apps.get_model('api', 'UserProfile')
    UserProfile.objects.filter(can_manage_requests=True).update(can_manage_boarding=True)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_dog_daily_rate_userprofile_can_manage_payments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="boarding_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-night boarding rate override for this dog. Blank = standard boarding price from Service Pricing. Staff-only field.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_manage_boarding",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user can approve/deny and edit boarding requests.",
            ),
        ),
        migrations.RunPython(backfill_can_manage_boarding, migrations.RunPython.noop),
    ]
