# Generated by Django 5.2.10 on 2026-07-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_dog_boarding_rate_userprofile_can_manage_boarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="boarding_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-night boarding rate for this customer. Blank = standard boarding price from Service Pricing.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daycare_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-day daycare rate for this customer. Blank = standard day care price from Service Pricing.",
                max_digits=6,
                null=True,
            ),
        ),
    ]
