# Generated by Django 5.2.10 on 2026-07-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_userprofile_boarding_rate_userprofile_daycare_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="is_adjustment",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="Number of attended days (1 for adjustments)."
            ),
        ),
    ]
