# Generated by Django 5.2.10 on 2026-07-05 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_invoiceline_is_adjustment_alter_invoiceline_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billed_dog",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the invoice is in a dog's name because the dog has no client attached.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="api.dog",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("billed_dog__isnull", False),
                    models.Q(("status", "VOID"), _negated=True),
                ),
                fields=("billed_dog", "period_year", "period_month"),
                name="uniq_active_invoice_per_dog_period",
            ),
        ),
    ]
