# Generated by Django 5.2.10 on 2026-07-05 15:26

from django.db import migrations, models


def _flag_app_billed(apps, schema_editor):
    """Customers/dogs that already have a staff-SENT app invoice are clearly on
    the new system — keep auto-generating for them. Everyone else defaults to
    MANUAL (invoiced by hand in Xero) until staff migrate them, so the monthly
    run can't double-bill customers still on the manual workflow. DRAFT-only
    invoices don't count: those were auto-generated, not a staff decision."""
    Invoice = apps.get_model('api', 'Invoice')
    UserProfile = apps.get_model('api', 'UserProfile')
    Dog = apps.get_model('api', 'Dog')

    sent = Invoice.objects.filter(status__in=('SENT', 'PART_PAID', 'PAID'))
    customer_ids = sent.exclude(customer__isnull=True).values_list('customer_id', flat=True).distinct()
    UserProfile.objects.filter(user_id__in=list(customer_ids)).update(billing_mode='APP')
    dog_ids = sent.exclude(billed_dog__isnull=True).values_list('billed_dog_id', flat=True).distinct()
    Dog.objects.filter(id__in=list(dog_ids)).update(billing_mode='APP')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_invoice_billed_dog_alter_invoice_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='billing_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual — invoiced directly in Xero'), ('APP', 'App — monthly invoices auto-generated')], default='MANUAL', help_text="Only used when no client is attached: whether monthly invoices are auto-generated in the dog's name (APP) or the business invoices by hand in Xero (MANUAL).", max_length=6),
        ),
        migrations.AddField(
            model_name='dog',
            name='xero_contact_id',
            field=models.CharField(blank=True, default='', help_text='Pinned Xero ContactID for dog-name invoices; backfilled on first push.', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xero_emailed_at',
            field=models.DateTimeField(blank=True, help_text='When Xero was asked to email this invoice to the customer (blank = not emailed).', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual — invoiced directly in Xero'), ('APP', 'App — monthly invoices auto-generated')], default='MANUAL', help_text='MANUAL customers are skipped by monthly invoice generation (the business invoices them by hand in Xero); APP customers get auto-generated invoices.', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xero_contact_id',
            field=models.CharField(blank=True, default='', help_text='Pinned Xero ContactID for this customer, so invoices attach to their existing Xero contact instead of matching by email/name (which can create duplicates). Set via the reconciliation screen or backfilled on first push.', max_length=64),
        ),
        migrations.RunPython(_flag_app_billed, migrations.RunPython.noop),
    ]
