# Generated by Django 5.2.10 on 2026-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_clear_superseded_removed_assignments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="boardingrequesthistory",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="boardingrequesthistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=10,
            ),
        ),
    ]
