# Generated by Django 5.2.10 on 2026-07-24 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_boardingrequest_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('PART_PAID', 'Partially paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('xero_payment_id', ''), _negated=True), fields=('invoice', 'xero_payment_id'), name='uniq_xero_payment_per_invoice'),
        ),
    ]
