# Generated by Django 5.2.10 on 2026-07-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_create_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadworkIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('STREET_MANAGER', 'DfT Street Manager'), ('MANUAL', 'Reported by staff')], default='STREET_MANAGER', max_length=20)),
                ('external_ref', models.CharField(blank=True, db_index=True, help_text='Permit reference from the source feed. Used to de-duplicate updates.', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('town', models.CharField(blank=True, default='', max_length=255)),
                ('highway_authority', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('traffic_management', models.CharField(blank=True, default='', help_text="Raw traffic management type from the feed, e.g. 'road_closure'.", max_length=100)),
                ('severity', models.CharField(choices=[('HIGH', 'Road closed'), ('MEDIUM', 'Delays likely'), ('LOW', 'Minor works')], default='LOW', max_length=10)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, help_text='Last message received for this permit, kept for debugging feed changes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'street'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='api_roadwor_start_d_f175f2_idx'), models.Index(fields=['is_cancelled', 'start_date', 'end_date'], name='api_roadwor_is_canc_9be4c7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_ref__gt', '')), fields=('source', 'external_ref'), name='unique_roadwork_per_source_ref')],
            },
        ),
    ]
