# Generated by Django 5.2.10 on 2026-08-14 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0077_roadworkissue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Short summary, e.g. "Scuffle in the back paddock".',
                        max_length=200,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("SCUFFLE", "Scuffle / fight"),
                            ("BITE", "Bite"),
                            ("INJURY", "Injury"),
                            ("ILLNESS", "Illness"),
                            ("ESCAPE", "Escape / loose dog"),
                            ("PROPERTY", "Property damage"),
                            ("TRANSPORT", "Transport / vehicle"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Minor"),
                            ("MEDIUM", "Moderate"),
                            ("HIGH", "Serious"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("MONITORING", "Monitoring"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where it happened — paddock, van, on a walk.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What happened, in the reporter's own words."
                    ),
                ),
                (
                    "injuries",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Injuries overall. Per-dog detail lives on IncidentDog.",
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What staff did at the time — separated, first aid, sent home.",
                    ),
                ),
                (
                    "vet_required",
                    models.BooleanField(
                        default=False, help_text="A vet was involved or needs to be."
                    ),
                ),
                (
                    "vet_details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Practice seen, treatment given, follow-up needed.",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, default="", help_text="How it was closed out."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_present",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Staff who witnessed or dealt with the incident.",
                        related_name="incidents_present_at",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IncidentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.incident",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentDog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("INVOLVED", "Involved"),
                            ("INSTIGATOR", "Instigator"),
                            ("INJURED", "Injured"),
                            ("PRESENT", "Present / witness"),
                        ],
                        default="INVOLVED",
                        max_length=20,
                    ),
                ),
                (
                    "injuries",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Injuries to this dog specifically.",
                    ),
                ),
                ("owner_notified", models.BooleanField(default=False)),
                ("owner_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_entries",
                        to="api.dog",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dog_entries",
                        to="api.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("incident", "dog")},
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="dogs",
            field=models.ManyToManyField(
                blank=True,
                related_name="incidents",
                through="api.IncidentDog",
                to="api.dog",
            ),
        ),
        migrations.CreateModel(
            name="IncidentMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("PHOTO", "Photo"), ("VIDEO", "Video")],
                        default="PHOTO",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(max_length=150, upload_to="incidents/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        max_length=150,
                        null=True,
                        upload_to="incidents/thumbnails/",
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="api.incident",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Incident media",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["-occurred_at"], name="api_inciden_occurre_6ff2b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["status"], name="api_inciden_status_372bb8_idx"),
        ),
    ]
