# Generated by Django 5.2.10 on 2026-08-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_incident_incidentcomment_incidentdog_incident_dogs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailydogassignment",
            name="from_boarding",
            field=models.BooleanField(
                default=False,
                help_text="This attendance was booked automatically from an approved boarding stay.",
            ),
        ),
    ]
