# Generated by Django 5.2.10 on 2026-08-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_dailydogassignment_from_boarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receives_business_alerts',
            field=models.BooleanField(default=False, help_text='Receive business-owner oversight alerts (e.g. a staff member sending a traffic delay alert). Intended for the business owner.'),
        ),
    ]
