# Generated by Django 5.2.10 on 2026-08-28 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_userprofile_receives_business_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_manage_staff',
            field=models.BooleanField(default=False, help_text='Designates whether this user can manage staff: the Staff Management section (pay, employment details, meetings, appraisals, sickness and training records), plus setting working days and approving/denying time off requests.'),
        ),
        migrations.CreateModel(
            name='SicknessAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Blank while the staff member is still off.', null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('notes', models.TextField(blank=True, default='', help_text='Return-to-work notes, fit note details, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sickness_absences_recorded', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sickness_absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sickness absences',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_date', models.DateField()),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, help_text='1 (poor) to 5 (excellent).', null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('areas_for_improvement', models.TextField(blank=True, default='')),
                ('goals', models.TextField(blank=True, default='', help_text='Objectives agreed for the next period.')),
                ('staff_comments', models.TextField(blank=True, default='', help_text="The staff member's own comments, added after sharing.")),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SHARED', 'Shared with staff member'), ('ACKNOWLEDGED', 'Acknowledged by staff member')], default='DRAFT', max_length=15)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_given', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appraisal_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffHRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('employment_start_date', models.DateField(blank=True, null=True)),
                ('employment_end_date', models.DateField(blank=True, help_text='Set when the staff member leaves.', null=True)),
                ('holiday_allowance_days', models.DecimalField(decimal_places=1, default=28, help_text='Paid holiday days per calendar year (UK statutory minimum for full time is 28 including bank holidays).', max_digits=4)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('emergency_contact_relationship', models.CharField(blank=True, default='', max_length=50)),
                ('manager_notes', models.TextField(blank=True, default='', help_text='Private manager notes; never shown to the staff member.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff HR record',
            },
        ),
        migrations.CreateModel(
            name='StaffMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('ONE_TO_ONE', 'One-to-one'), ('TEAM', 'Team meeting'), ('RETURN_TO_WORK', 'Return to work'), ('OTHER', 'Other')], default='ONE_TO_ONE', max_length=15)),
                ('scheduled_for', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('agenda', models.TextField(blank=True, default='')),
                ('minutes', models.TextField(blank=True, default='', help_text='Notes recorded after the meeting.')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='staff_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_meetings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='StaffTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Canine First Aid', max_length=200)),
                ('provider', models.CharField(blank=True, default='', max_length=200)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Blank if the qualification does not expire.', null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records_added', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('SALARY', 'Annual salary')], default='HOURLY', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='£ per hour for HOURLY, £ per year for SALARY.', max_digits=9)),
                ('effective_from', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_rates_set', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
                'constraints': [models.UniqueConstraint(fields=('staff_member', 'effective_from'), name='unique_pay_rate_per_staff_date')],
            },
        ),
    ]
