# Generated by Django 5.2.10 on 2026-08-28 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_userprofile_can_manage_staff_sicknessabsence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_compliance',
            field=models.BooleanField(default=False, help_text='Designates whether this user can manage the safety & compliance register (add/edit checks and schedules) and receive due-check reminders. Any staff member can record a completed check.'),
        ),
        migrations.CreateModel(
            name='ComplianceCheckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FIRE', 'Fire safety'), ('ELECTRICAL', 'Electrical'), ('HEALTH_SAFETY', 'Health & safety'), ('HYGIENE', 'Hygiene & pest control'), ('DOCUMENTS', 'Licences, insurance & documents'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SIX_MONTHLY', 'Every 6 months'), ('ANNUAL', 'Yearly'), ('TWO_YEARLY', 'Every 2 years'), ('FIVE_YEARLY', 'Every 5 years'), ('AD_HOC', 'As needed (no schedule)')], default='MONTHLY', max_length=12)),
                ('description', models.TextField(blank=True, default='', help_text='What the check involves / who normally does it.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive checks keep their history but stop being due.')),
                ('advance_notice_sent', models.BooleanField(default=False, help_text='30-day advance reminder sent for the current cycle (long-cycle checks only).')),
                ('due_notice_sent', models.BooleanField(default=False, help_text='Due/overdue reminder sent for the current cycle.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField()),
                ('result', models.CharField(choices=[('PASS', 'All OK'), ('ISSUES', 'Issues found')], default='PASS', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_logs', to=settings.AUTH_USER_MODEL)),
                ('check_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.compliancechecktype')),
            ],
            options={
                'ordering': ['-performed_on', '-id'],
            },
        ),
    ]
