# Generated by Django 5.2.10 on 2026-08-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_seed_compliance_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='contact_number',
            field=models.CharField(blank=True, default='', help_text="Day-to-day contact number for this dog's household.", max_length=50),
        ),
        migrations.AddField(
            model_name='dog',
            name='emergency_contact_number',
            field=models.CharField(blank=True, default='', help_text="Emergency contact if the main number doesn't answer — a name can be included, e.g. '07700 900123 (Sue, neighbour)'.", max_length=50),
        ),
    ]
