# Generated by Django 5.2.10 on 2026-08-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_dog_contact_number_dog_emergency_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='last_vaccination_date',
            field=models.DateField(blank=True, help_text='When the dog was last vaccinated. Auto-updated when a vaccination record is added; over a year ago flags the dog as overdue.', null=True),
        ),
    ]
