# Generated by Django 5.2.10 on 2026-09-04 10:43

import api.certificates
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_backfill_last_vaccination_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='annual_vaccination_reminder_sent_for',
            field=models.DateField(blank=True, help_text='Bookkeeping for send_vaccination_reminders: the last_vaccination_date the one-week-before push was sent for.', null=True),
        ),
        migrations.CreateModel(
            name='VaccinationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, storage=api.certificates.private_storage, upload_to=api.certificates.certificate_upload_path)),
                ('vaccination_date', models.DateField(blank=True, help_text='The vaccination date this certificate evidences — the value of the date field when it was attached.', null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_certificates', to='api.dog')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vaccination_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
