# Generated by Django 5.2.10 on 2026-09-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_vaccination_certificates_and_annual_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroconnection',
            name='unassigned_contact_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
