# Generated by Django 5.2.10 on 2026-09-15 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_move_pickup_instructions_to_dogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=100)),
                ('actor_name', models.CharField(blank=True, help_text='Display name at the time; blank = system.', max_length=150)),
                ('action', models.CharField(choices=[('CREATED', 'Added'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('OWNER_CHANGED', 'Owner changed'), ('VACCINATION', 'Vaccination'), ('PHOTO', 'Gallery'), ('NOTE', 'Note')], max_length=20)),
                ('source', models.CharField(choices=[('APP', 'App'), ('OWNER_REQUEST', 'Approved owner request'), ('BOOKING_FORM', 'Booking form'), ('ADMIN', 'Admin site'), ('SYSTEM', 'System')], default='APP', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=list, help_text='[{field, label, old, new}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_changes', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='api.dog')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
