# Generated by Django 5.2.10 on 2026-09-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_activity_log_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportquery',
            name='staff_has_unread',
            field=models.BooleanField(default=False, help_text='True from an owner message until staff reply or resolve — staff merely viewing the thread does not clear it'),
        ),
    ]
