# Generated by Django 5.2.17 on 2026-09-15 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_support_query_unread_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerHandoverDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leg', models.CharField(choices=[('DROP_OFF', 'Owner drop-offs'), ('COLLECTION', 'Owner collections')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_owner_handover_duties', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(blank=True, help_text='Staff member responsible for meeting the owners on this leg that day.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_handover_duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'leg'],
                'unique_together': {('date', 'leg')},
            },
        ),
    ]
