# Generated by Django 5.2.17 on 2026-09-19 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_owner_handover_duty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogchangelog',
            name='source',
            field=models.CharField(choices=[('APP', 'App'), ('OWNER_REQUEST', 'Approved owner request'), ('BOOKING_FORM', 'Booking form'), ('LINK_REQUEST', 'Link request'), ('WEBSITE', 'Website'), ('ADMIN', 'Admin site'), ('SYSTEM', 'System')], default='APP', max_length=20),
        ),
        migrations.CreateModel(
            name='DogLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(help_text="The dog's name as the client knows it.", max_length=100)),
                ('postcode', models.CharField(blank=True, help_text='Pickup postcode, matched against the postcode on the dog.', max_length=10)),
                ('phone_number', models.CharField(blank=True, help_text="The client's number, matched against the contact numbers on the dog.", max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Anything else that helps staff find the dog (breed, usual days, other family members).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('denial_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(blank=True, help_text='The dog the account was linked to on approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_requests', to='api.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_link_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dog_link_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
