# Generated by Django 5.2.17 on 2026-09-20 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_dog_link_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('dog_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.dog')),
                ('dog_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.dog')),
            ],
            options={
                'ordering': ['date', 'dog_a_id', 'dog_b_id'],
                'unique_together': {('date', 'dog_a', 'dog_b')},
            },
        ),
    ]
