# Generated by Django 5.2.17 on 2026-09-20 18:56

import api.certificates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_conflict_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='certificate_reminder_anchor',
            field=models.DateField(blank=True, help_text='Bookkeeping for send_vaccination_reminders: the certificate_needed_since date the escalating certificate reminders are counting from.', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='certificate_reminder_last_sent',
            field=models.DateField(blank=True, help_text='When the owners were last pushed about the certificate, by the daily command or a staff member.', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='certificate_reminders_sent',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many escalating certificate reminders have gone out for the current anchor.'),
        ),
        migrations.AddField(
            model_name='intakedog',
            name='certificate_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='intakedog',
            name='certificate_file',
            field=models.FileField(blank=True, max_length=200, storage=api.certificates.private_storage, upload_to=api.certificates.intake_certificate_upload_path),
        ),
        migrations.AddField(
            model_name='intakedog',
            name='certificate_original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='intakedog',
            name='certificate_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intakedog',
            name='last_vaccination_date',
            field=models.DateField(blank=True, help_text="The date on the certificate; becomes the dog's last_vaccination_date on approval.", null=True),
        ),
    ]
