# Generated by Django 5.2.17 on 2026-09-28 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0099_book_owner_driven_dogs_to_house"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cert_type",
                    models.CharField(
                        choices=[("DBS", "DBS check")], default="DBS", max_length=20
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BASIC", "Basic"),
                            ("STANDARD", "Standard"),
                            ("ENHANCED", "Enhanced"),
                            ("ENHANCED_BARRED", "Enhanced with barred list(s)"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "renewal_date",
                    models.DateField(
                        blank=True,
                        help_text="When it should be rechecked. A DBS certificate never expires itself; blank if not rechecked.",
                        null=True,
                    ),
                ),
                (
                    "on_update_service",
                    models.BooleanField(
                        default=False,
                        help_text="Subscribed to the DBS Update Service, so it can be status-checked online.",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["cert_type", "-issue_date", "-id"],
            },
        ),
    ]
