"""
Django settings for p4td_backend project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (development only)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# In production, this MUST be set via environment variable
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes'):
        SECRET_KEY = 'django-insecure-dev-secret-only-for-local-development'
    else:
        raise ValueError("DJANGO_SECRET_KEY environment variable is required in production")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False for safety
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# Allowed hosts - configure via environment variable
# Example: DJANGO_ALLOWED_HOSTS=api.example.com,localhost
ALLOWED_HOSTS = [
    host.strip() 
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Always allow localhost and 127.0.0.1 for health checks.
# This is safe even in production: the container/compose healthcheck curls
# http://localhost:8000/healthz/ from *inside* the container, and prod does
# NOT publish the app port externally (see docker-compose.prod.yml / I8) — only
# Caddy can reach the app, over the internal Docker network. The usual risk of a
# permissive ALLOWED_HOSTS (Host-header poisoning of password-reset links) does
# not apply here because the reset flow is OTP-based (a 6-digit code emailed to
# the user, exchanged for a token — see api/views.py request_password_reset);
# no absolute reset URLs are built from the request Host.
if 'localhost' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('localhost')
if '127.0.0.1' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('127.0.0.1')

# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'corsheaders',
    'django_summernote',
    'django_recaptcha',
    'api',
    'website',
]

MIGRATION_MODULES = {
    'django_summernote': 'django_summernote_migrations',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files efficiently
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'p4td_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.website_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'p4td_backend.wsgi.application'

# =============================================================================
# DATABASE
# =============================================================================

# Use PostgreSQL in production, SQLite for development
if os.environ.get('DATABASE_URL') or os.environ.get('RDS_HOSTNAME'):
    # Production PostgreSQL (RDS)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('RDS_DB_NAME', 'p4td'),
            'USER': os.environ.get('RDS_USERNAME', 'postgres'),
            'PASSWORD': os.environ.get('RDS_PASSWORD', ''),
            'HOST': os.environ.get('RDS_HOSTNAME', 'localhost'),
            'PORT': os.environ.get('RDS_PORT', '5432'),
        }
    }
else:
    # Development SQLite
    _db_path = os.environ.get('DJANGO_DB_PATH')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _db_path if _db_path else BASE_DIR / 'db.sqlite3',
        }
    }

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 10}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    {'NAME': 'api.validators.PasswordComplexityValidator'},
]
# Note: Passwords do not expire. Complexity is enforced at creation/change time only.

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# =============================================================================
# MEDIA FILES (User uploads)
# =============================================================================

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# REVERSE PROXY SETTINGS (Caddy)
# =============================================================================

# Trust X-Forwarded-Host header from Caddy so build_absolute_uri() returns
# the correct public URL instead of the internal Docker hostname.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# =============================================================================
# EMAIL SETTINGS
# =============================================================================

EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@paws4thoughtdogs.co.uk')


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Damp brute-force attempts on anonymous endpoints (login, registration,
    # password reset). Authenticated app traffic is never anon-throttled.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'password_reset': '5/hour',
        'password_reset_confirm': '10/hour',
    },
    # One reverse proxy (Caddy) in front of gunicorn — throttle the real
    # client IP from X-Forwarded-For, not the proxy's.
    'NUM_PROXIES': 1,
}

# Require Privacy Policy acceptance at sign-up via a custom user-create
# serializer (records when/which version the user accepted).
DJOSER = {
    'SERIALIZERS': {
        'user_create': 'api.serializers.UserCreateWithPrivacySerializer',
    },
}

# =============================================================================
# CORS SETTINGS
# =============================================================================

# In production, specify exact origins
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]

# Allow all origins if:
# 1. CORS_ALLOW_ALL_ORIGINS env var is set to True, OR
# 2. DEBUG mode and no specific origins configured
_cors_allow_all_env = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False').lower() in ('true', '1', 'yes')
if _cors_allow_all_env or (DEBUG and not CORS_ALLOWED_ORIGINS):
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False

# Make an open CORS policy loud — it must never silently resolve True in
# production (e.g. if DEBUG is flipped on during an incident with no origins
# configured). The warning surfaces in logs at startup (B45).
if CORS_ALLOW_ALL_ORIGINS:
    import logging
    logging.getLogger('django.security').warning(
        'CORS_ALLOW_ALL_ORIGINS is enabled — every origin can call the API. '
        'This is only safe for local development; never enable it in production.'
    )


# =============================================================================
# CSRF TRUSTED ORIGINS
# =============================================================================

# Required for form submissions from external domains (e.g. the website)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# =============================================================================
# SECURITY HEADERS (Production)
# =============================================================================

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Required for Summernote editor iframes

    # HTTPS is provisioned and terminated by Caddy (see Caddyfile). Django learns
    # the request was HTTPS via SECURE_PROXY_SSL_HEADER (set above), so these
    # flags are safe to enable in production.
    SECURE_SSL_REDIRECT = True          # Redirect any plain HTTP to HTTPS
    SESSION_COOKIE_SECURE = True        # Session cookie only sent over HTTPS
    CSRF_COOKIE_SECURE = True           # CSRF cookie only sent over HTTPS
    SESSION_COOKIE_HTTPONLY = True      # Block JS access to the session cookie

    # HTTP Strict Transport Security: tell browsers to use HTTPS for a year,
    # cover subdomains, and allow preload-list inclusion.
    SECURE_HSTS_SECONDS = 31536000      # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# RECAPTCHA (v3)
# =============================================================================

# Public site key is rendered in HTML; private key verifies tokens server-side.
# Generate at https://www.google.com/recaptcha/admin (choose reCAPTCHA v3).
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', '')
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', '')
# Minimum score (0.0 = bot, 1.0 = human) required for the form to validate.
RECAPTCHA_REQUIRED_SCORE = float(os.environ.get('RECAPTCHA_REQUIRED_SCORE', '0.5'))

# =============================================================================
# POSTCODE -> ADDRESS LOOKUP (optional)
# =============================================================================

# Powers the in-app "look up postcode" button on a dog's Registered Vet field.
# The key is kept server-side; the app calls /api/postcode/lookup/ which proxies
# to the provider. Leave POSTCODE_LOOKUP_API_KEY blank to disable the feature
# (the vet field then works as a plain text box).
# Default provider is getAddress.io (https://getaddress.io). Sign up, create an
# API key, then set POSTCODE_LOOKUP_API_KEY in the environment / .env file.
POSTCODE_LOOKUP_API_KEY = os.environ.get('POSTCODE_LOOKUP_API_KEY', '')
POSTCODE_LOOKUP_PROVIDER = os.environ.get('POSTCODE_LOOKUP_PROVIDER', 'getaddress')

# =============================================================================
# XERO ACCOUNTING INTEGRATION (optional)
# =============================================================================

# Powers monthly customer invoicing: invoices are pushed to Xero, owners pay
# through the Xero online-invoice link, and payment status syncs back. Create
# a "Web app" at https://developer.xero.com with the redirect URI set to
# exactly XERO_REDIRECT_URI (https://<domain>/api/xero/callback/), then a
# superuser completes the one-time consent via POST /api/xero/connect/.
# Leave the client credentials blank to disable the integration — invoicing
# still works locally, just without the online payment link.
XERO_CLIENT_ID = os.environ.get('XERO_CLIENT_ID', '')
XERO_CLIENT_SECRET = os.environ.get('XERO_CLIENT_SECRET', '')
XERO_REDIRECT_URI = os.environ.get('XERO_REDIRECT_URI', '')
# Xero account code (bank / undeposited funds) that staff-recorded manual
# payments are booked against in Xero. Blank = manual payments stay app-only.
XERO_PAYMENT_ACCOUNT_CODE = os.environ.get('XERO_PAYMENT_ACCOUNT_CODE', '')

# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# =============================================================================
# SUMMERNOTE (WYSIWYG Editor)
# =============================================================================

SUMMERNOTE_CONFIG = {
    'summernote': {
        'width': '100%',
        'height': '500',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'clear']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['insert', ['link', 'picture', 'hr']],
            ['misc', ['undo', 'redo']],
            ['view', ['fullscreen', 'codeview']],
        ],
    },
    'attachment_require_authentication': True,
}

# =============================================================================
# ERROR MONITORING (Sentry — optional)
# =============================================================================

# Enabled only when SENTRY_DSN is set in the environment. Dev and CI/tests have
# no DSN, so this stays a complete no-op there. The import is guarded so a
# missing sentry-sdk package can never break startup.
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    try:
        import sentry_sdk
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            # Sample a small fraction of transactions for performance tracing.
            traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.05')),
            environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
            # Do not attach PII (user emails, request bodies) to events.
            send_default_pii=False,
        )
    except ImportError:
        # sentry-sdk not installed; skip monitoring rather than crash.
        pass
