"""Xero accounting integration (OAuth2 + Accounting API).

The business runs its books in Xero. Monthly invoices generated by
``api.billing`` are pushed here as ACCREC sales invoices, owners pay via the
Xero online-invoice URL, and a periodic sync pulls payments back so the app's
ledger converges with Xero's.

Connection model: client id/secret live in env vars (``XERO_CLIENT_ID`` /
``XERO_CLIENT_SECRET``); the rotating refresh token + tenant id captured by
the one-time superuser consent flow live in the :class:`api.models.XeroConnection`
pk=1 singleton. Everything degrades gracefully — callers treat
:class:`XeroNotConnected` as "feature off".

Uses the Python standard library only (``urllib``) so no extra pip dependency
is introduced — adding one to a single requirements file breaks the prod
Docker build. All network I/O goes through :func:`_token_request` and
:func:`_api_request`, which tests patch directly.
"""
import base64
import json as _json
import logging
import secrets as _secrets
import urllib.error
import urllib.parse
import urllib.request

from django.conf import settings
from django.db import transaction
from django.utils import timezone

logger = logging.getLogger(__name__)

AUTH_URL = 'https://login.xero.com/identity/connect/authorize'
TOKEN_URL = 'https://identity.xero.com/connect/token'
CONNECTIONS_URL = 'https://api.xero.com/connections'
API_BASE = 'https://api.xero.com/api.xro/2.0'
SCOPES = 'offline_access accounting.transactions accounting.contacts'

# How long an in-flight authorize state stays valid.
STATE_MAX_AGE_SECONDS = 600


class XeroError(Exception):
    """A Xero API error the caller should surface or store."""


class XeroNotConnected(XeroError):
    """Xero is not configured/connected — callers treat the feature as off."""


class XeroAuthError(XeroError):
    """The stored credentials are dead (e.g. rotated refresh token lost);
    a superuser must reconnect."""


def is_configured():
    """Whether the env-var app credentials are present."""
    return bool(getattr(settings, 'XERO_CLIENT_ID', '') and getattr(settings, 'XERO_CLIENT_SECRET', ''))


# ---------------------------------------------------------------------------
# HTTP primitives — the ONLY functions that touch the network. Tests patch
# these (mirroring api.geocoding._fetch_postcodes_io).
# ---------------------------------------------------------------------------

def _token_request(form):
    """POST ``form`` to the Xero token endpoint with HTTP Basic app credentials.

    Returns the parsed JSON dict. Raises :class:`XeroAuthError` on
    ``invalid_grant`` (dead refresh token / bad code), :class:`XeroError` on
    anything else.
    """
    basic = base64.b64encode(
        f"{settings.XERO_CLIENT_ID}:{settings.XERO_CLIENT_SECRET}".encode()
    ).decode()
    req = urllib.request.Request(
        TOKEN_URL,
        data=urllib.parse.urlencode(form).encode(),
        headers={
            'Authorization': f'Basic {basic}',
            'Content-Type': 'application/x-www-form-urlencoded',
            'User-Agent': 'p4td-backend',
        },
        method='POST',
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return _json.loads(resp.read().decode('utf-8'))
    except urllib.error.HTTPError as exc:
        try:
            detail = exc.read().decode('utf-8')
        except Exception:
            detail = ''
        if 'invalid_grant' in detail:
            raise XeroAuthError('Xero refused the stored credentials (invalid_grant) — reconnect Xero.')
        raise XeroError(f'Xero token endpoint error (HTTP {exc.code}).')
    except (urllib.error.URLError, TimeoutError, ValueError):
        raise XeroError('Could not reach the Xero token endpoint.')


def _api_request(method, path, access_token, tenant_id=None, payload=None, params=None):
    """Call the Xero API and return the parsed JSON dict.

    ``path`` is absolute (starts with http) or relative to :data:`API_BASE`.
    Raises :class:`XeroError` with the response detail on failure.
    """
    url = path if path.startswith('http') else f'{API_BASE}/{path.lstrip("/")}'
    if params:
        url = f'{url}?{urllib.parse.urlencode(params)}'
    headers = {
        'Authorization': f'Bearer {access_token}',
        'Accept': 'application/json',
        'User-Agent': 'p4td-backend',
    }
    if tenant_id:
        headers['xero-tenant-id'] = tenant_id
    data = None
    if payload is not None:
        data = _json.dumps(payload).encode('utf-8')
        headers['Content-Type'] = 'application/json'
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = resp.read().decode('utf-8')
            return _json.loads(body) if body else {}
    except urllib.error.HTTPError as exc:
        try:
            detail = exc.read().decode('utf-8')[:500]
        except Exception:
            detail = ''
        if exc.code == 401:
            raise XeroAuthError(f'Xero rejected the access token (HTTP 401). {detail}')
        raise XeroError(f'Xero API error (HTTP {exc.code}): {detail}')
    except (urllib.error.URLError, TimeoutError, ValueError):
        raise XeroError('Could not reach the Xero API.')


# ---------------------------------------------------------------------------
# OAuth2 connection flow
# ---------------------------------------------------------------------------

def build_authorize_url():
    """Create the Xero consent URL for the superuser connect flow.

    Stores a fresh CSRF ``state`` on the connection singleton — the callback
    arrives as a bare browser GET with no session, so this state token is what
    authenticates it.
    """
    from .models import XeroConnection

    if not is_configured():
        raise XeroNotConnected('Xero client credentials are not configured on the server.')
    if not getattr(settings, 'XERO_REDIRECT_URI', ''):
        raise XeroNotConnected('XERO_REDIRECT_URI is not configured on the server.')

    conn = XeroConnection.load()
    conn.oauth_state = _secrets.token_urlsafe(32)
    conn.oauth_state_created_at = timezone.now()
    conn.save()

    query = urllib.parse.urlencode({
        'response_type': 'code',
        'client_id': settings.XERO_CLIENT_ID,
        'redirect_uri': settings.XERO_REDIRECT_URI,
        'scope': SCOPES,
        'state': conn.oauth_state,
    })
    return f'{AUTH_URL}?{query}'


def handle_callback(code, state):
    """Complete the OAuth2 authorize flow: validate state, exchange the code,
    resolve the tenant, and persist the connection. Returns the tenant name.
    """
    from .models import XeroConnection

    conn = XeroConnection.load()
    state_age_ok = (
        conn.oauth_state_created_at is not None
        and (timezone.now() - conn.oauth_state_created_at).total_seconds() < STATE_MAX_AGE_SECONDS
    )
    if not state or not conn.oauth_state or not _secrets.compare_digest(state, conn.oauth_state) or not state_age_ok:
        raise XeroAuthError('Invalid or expired authorisation state. Start the connect flow again.')

    # One-shot: clear the state before the exchange so a replayed redirect fails.
    conn.oauth_state = ''
    conn.oauth_state_created_at = None
    conn.save()

    tokens = _token_request({
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': settings.XERO_REDIRECT_URI,
    })

    connections = _api_request('GET', CONNECTIONS_URL, tokens['access_token'])
    if not connections:
        raise XeroError('The Xero account has no authorised organisations.')
    tenant = connections[0]

    conn.tenant_id = tenant.get('tenantId', '')
    conn.tenant_name = tenant.get('tenantName', '')
    conn.refresh_token = tokens.get('refresh_token', '')
    conn.access_token = tokens.get('access_token', '')
    conn.access_token_expires_at = timezone.now() + timezone.timedelta(seconds=int(tokens.get('expires_in', 1800)) - 60)
    conn.connected_at = timezone.now()
    conn.save()
    return conn.tenant_name


def disconnect():
    """Forget the stored Xero connection (tokens + tenant)."""
    from .models import XeroConnection

    conn = XeroConnection.load()
    conn.tenant_id = ''
    conn.tenant_name = ''
    conn.refresh_token = ''
    conn.access_token = ''
    conn.access_token_expires_at = None
    conn.oauth_state = ''
    conn.oauth_state_created_at = None
    conn.connected_at = None
    conn.save()


def get_access_token():
    """Return a valid access token, refreshing (and rotating) if needed.

    Xero refresh tokens are single-use: each refresh returns a NEW refresh
    token and invalidates the old one. Two workers refreshing concurrently
    would clobber each other, so the refresh runs under ``select_for_update``
    on the singleton row and re-checks expiry after acquiring the lock —
    the second worker just reads the token the first one stored.
    """
    from .models import XeroConnection

    conn = XeroConnection.load()
    if not conn.is_connected:
        raise XeroNotConnected('Xero is not connected.')

    now = timezone.now()
    if conn.access_token and conn.access_token_expires_at and conn.access_token_expires_at > now:
        return conn.access_token

    try:
        with transaction.atomic():
            conn = XeroConnection.objects.select_for_update().get(pk=1)
            if not conn.is_connected:
                raise XeroNotConnected('Xero is not connected.')
            now = timezone.now()
            # Another worker may have refreshed while we waited on the lock.
            if conn.access_token and conn.access_token_expires_at and conn.access_token_expires_at > now:
                return conn.access_token
            tokens = _token_request({
                'grant_type': 'refresh_token',
                'refresh_token': conn.refresh_token,
            })
            conn.access_token = tokens.get('access_token', '')
            # Persist the rotated single-use refresh token BEFORE releasing the lock.
            conn.refresh_token = tokens.get('refresh_token', conn.refresh_token)
            conn.access_token_expires_at = now + timezone.timedelta(seconds=int(tokens.get('expires_in', 1800)) - 60)
            conn.save()
            return conn.access_token
    except XeroAuthError:
        # Dead refresh token — clear the connection so is_connected flips false
        # and /api/xero/status/ tells the superuser to reconnect. Must happen
        # OUTSIDE the atomic block: the propagating exception rolls that back.
        conn = XeroConnection.load()
        conn.refresh_token = ''
        conn.access_token = ''
        conn.access_token_expires_at = None
        conn.save()
        raise


def _tenant_call(method, path, payload=None, params=None):
    """An authenticated Accounting API call against the connected tenant."""
    from .models import XeroConnection

    token = get_access_token()
    tenant_id = XeroConnection.load().tenant_id
    return _api_request(method, path, token, tenant_id, payload=payload, params=params)


# ---------------------------------------------------------------------------
# Accounting API operations used by api.billing
# ---------------------------------------------------------------------------

def _escape_where_value(value):
    """Escape a string for interpolation into a Xero ``where`` filter."""
    return value.replace('\\', '\\\\').replace('"', '\\"')


def _contact_display_name(user):
    name = f"{user.first_name} {user.last_name}".strip()
    return name or user.username


def find_or_create_contact(user):
    """Return the Xero ContactID for a customer, creating the contact if
    needed. Matches by email first (the stable key), then by display name."""
    email = (user.email or '').strip()
    if email:
        result = _tenant_call('GET', 'Contacts', params={
            'where': f'EmailAddress=="{_escape_where_value(email)}"',
        })
        contacts = result.get('Contacts') or []
        if contacts:
            return contacts[0]['ContactID']

    return find_or_create_contact_by_name(_contact_display_name(user), email=email)


def find_or_create_contact_by_name(name, email=''):
    """Return the Xero ContactID for a bare display name (e.g. an invoice in
    a dog's name), creating the contact if needed. The business can then
    attach an email address in Xero and send the invoice from there."""
    result = _tenant_call('GET', 'Contacts', params={
        'where': f'Name=="{_escape_where_value(name)}"',
    })
    contacts = result.get('Contacts') or []
    if contacts:
        return contacts[0]['ContactID']

    payload = {'Contacts': [{'Name': name}]}
    if email:
        payload['Contacts'][0]['EmailAddress'] = email
    result = _tenant_call('POST', 'Contacts', payload=payload)
    return result['Contacts'][0]['ContactID']


def create_invoice(invoice, contact_id):
    """Create an authorised ACCREC invoice in Xero from a local Invoice.

    ``LineAmountTypes: Inclusive`` keeps the app's gross total equal to the
    Xero total regardless of the org's default tax rate. Returns
    ``(InvoiceID, InvoiceNumber)``.
    """
    lines = [
        {
            'Description': line.description,
            'Quantity': line.quantity,
            'UnitAmount': float(line.unit_price),
        }
        for line in invoice.lines.all()
    ]
    payload = {
        'Invoices': [{
            'Type': 'ACCREC',
            'Contact': {'ContactID': contact_id},
            'Status': 'AUTHORISED',
            'LineAmountTypes': 'Inclusive',
            'Date': timezone.now().date().isoformat(),
            'DueDate': invoice.due_date.isoformat() if invoice.due_date else timezone.now().date().isoformat(),
            'Reference': f'Daycare {invoice.period_label}',
            'LineItems': lines,
        }],
    }
    result = _tenant_call('POST', 'Invoices', payload=payload)
    created = result['Invoices'][0]
    return created['InvoiceID'], created.get('InvoiceNumber', '')


def get_online_invoice_url(xero_invoice_id):
    """Return the customer-facing online invoice URL, or '' if unavailable."""
    result = _tenant_call('GET', f'Invoices/{xero_invoice_id}/OnlineInvoice')
    entries = result.get('OnlineInvoices') or []
    if entries:
        return entries[0].get('OnlineInvoiceUrl', '')
    return ''


def fetch_invoices(xero_invoice_ids):
    """Fetch invoices (with their Payments) by Xero id. Returns a list of
    invoice dicts. Callers chunk the ids; Xero caps the IDs filter length."""
    if not xero_invoice_ids:
        return []
    result = _tenant_call('GET', 'Invoices', params={'IDs': ','.join(xero_invoice_ids)})
    return result.get('Invoices') or []


def void_invoice(xero_invoice_id):
    """Void an invoice in Xero, mirroring an in-app void.

    Xero only allows voiding invoices with no payments applied — if payments
    exist there, this raises XeroError and the books need a manual credit
    note/refund instead.
    """
    _tenant_call('POST', 'Invoices', payload={
        'Invoices': [{'InvoiceID': xero_invoice_id, 'Status': 'VOIDED'}],
    })


def create_payment(xero_invoice_id, amount, payment_date, account_code):
    """Record a payment against a Xero invoice (used to mirror manual payments
    recorded in the app). Returns the Xero PaymentID."""
    payload = {
        'Payments': [{
            'Invoice': {'InvoiceID': xero_invoice_id},
            'Account': {'Code': account_code},
            'Date': payment_date.isoformat(),
            'Amount': float(amount),
        }],
    }
    result = _tenant_call('PUT', 'Payments', payload=payload)
    return result['Payments'][0]['PaymentID']
